require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ViroSample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'ViroReact', :path => '../node_modules/@viro-community/react-viro/ios/'
  pod 'ViroKit_static_lib', :path => '../node_modules/@viro-community/react-viro/ios/dist/ViroRenderer/static_lib'
end
